#!/bin/bash
# Generated by fishbowl. Runs a sample under the account that owns nothing.
#
# The researcher's shell and both agents run as {{ researcher_user }}, which is the account
# an agent's borrowed token is written for. A sample run under that uid could simply read
# the file, so it is run under {{ detonate_user }}: no credential is ever written for that
# account, the directory the courier writes into is closed to it, and the packet filter
# drops its traffic outright — a detonated sample has no network at all.
#
# This does not make a sample safe. It is one uid inside a machine that is itself the
# boundary; the network is only the most visible of the things it still shares.
set -euo pipefail

if [ "$#" -eq 0 ]; then
  echo "usage: detonate <command> [argument ...]" >&2
  exit 64
fi

exec sudo --non-interactive --user {{ detonate_user }} -- "$@"
