#!/bin/bash
# Generated by fishbowl. Runs a sample under the account that owns nothing.
#
# The researcher's shell and both agents run as {{ researcher_user }}, which is the account
# an agent's borrowed token is written for. A sample run under that uid could simply read
# the file, so it is run under {{ detonate_user }}: no credential is ever written for that
# account, and the directory the courier writes into is closed to it.
#
# This does not make a sample safe. It is one uid inside a machine that is itself the
# boundary, and every packet it sends is still audited or refused.
set -euo pipefail

if [ "$#" -eq 0 ]; then
  echo "usage: detonate <command> [argument ...]" >&2
  exit 64
fi

exec sudo --non-interactive --user {{ detonate_user }} -- "$@"
