#!/bin/sh
# Generated by fishbowl. What Claude Code shows in its status line inside a session.
#
# Claude Code hands this program a JSON description of the session on stdin after every
# turn — model, context use, subscription limits — and shows whatever it prints. None of
# that is repeated here: Claude Code already shows it, and what it cannot know is where it
# is running. The one thing a researcher should never lose track of is that this agent is
# inside the sandbox, so that is the whole line.
cat >/dev/null
printf 'Fishbowl\n'
