#!/bin/bash
# Generated by fishbowl. Runs a command under the account whose traffic is Tor or nothing.
#
# The researcher's shell and both agents run as {{ researcher_user }}, whose connections ride
# the session's base egress — under a red team session, the WARP tunnel. A command run
# through this wrapper is executed under {{ torsion_user }}: the packet filter redirects that
# uid's TCP to a dedicated gateway listener that carries it over Tor, resolves its DNS inside
# Tor, and refuses it while Tor is down — never the base route, never the machine's own
# address.
#
# sudo resets the environment it passes on, which is load-bearing here too: the credentials
# an agent was lent live in the wrapping process's environment, and a command sent to a
# target does not take them with it.
set -euo pipefail

if [ "$#" -eq 0 ]; then
  echo "usage: torsion <command> [argument ...]" >&2
  exit 64
fi

exec sudo --non-interactive --user {{ torsion_user }} -- "$@"
