[package]
name = "cyber-sandbox"
description = "Provisions isolated, fully audited security-research environments on macOS."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
cyber-sandbox-agents.workspace = true
cyber-sandbox-audit = { workspace = true, features = ["io"] }
cyber-sandbox-creds.workspace = true
cyber-sandbox-image.workspace = true
cyber-sandbox-runtime.workspace = true
anyhow.workspace = true
askama.workspace = true
clap.workspace = true
getrandom.workspace = true
inquire.workspace = true
jiff.workspace = true
nix = { workspace = true, features = ["fs", "process", "signal"] }
serde.workspace = true
serde_json.workspace = true
ssh-key.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
